# Generated by Django 4.1.6 on 2023-02-14 00:44

import django.core.validators
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to="images",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "jpg"])
                ],
            ),
        ),
    ]
