# Generated by Django 4.1.6 on 2023-02-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_datetime", models.DateTimeField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.image"
                    ),
                ),
            ],
        ),
    ]
